on:
  push:
    branches: [main,dev]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages("remotes")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}

      - name: "Cache R packages"
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: download system packages
        run: |
          sudo apt update
          sudo apt-get install \
            r-base-dev \
            build-essential \
            gdal-bin \
            libgdal-dev \
            libjq-dev \
            libssl-dev \
            libcurl4-openssl-dev \
            libxml2-dev \
            libprotobuf-dev \
            protobuf-compiler \
            libv8-dev \
            libssl-dev \
            libcairo2-dev \
            libgit2-dev

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}
